name: MoSCoW Pull Request Prioritization
description: 'MoSCoW Prioritization action to manage label-based requirements prioritization'
author: 'grevend'

branding:
  icon: 'check-circle'
  color: 'gray-dark'

inputs:
  token:
    description: 'The workflows GITHUB_TOKEN secret'
    required: false
    default: '${{ github.token }}'
  wont-have-label:
    description: 'Label to expect on low-priority PRs'
    required: false
    default: 'wont have'
  could-have-label:
    description: 'Label to expect on PRs of little relevance'
    required: false
    default: 'could have'
  should-have-label:
    description: 'Label to expect on non-critical PRs'
    required: false
    default: 'should have'
  must-have-label:
    description: 'Label to expect on essential PRs'
    required: false
    default: 'must have'

runs:
  using: 'node20'
  main: 'dist/index.js'
