name: MoSCoW Prioritization

on:
  pull_request_target:
    types: [labeled, opened, unlabeled, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: grevend/moscow-prioritization@v1.0.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'